// <auto-generated />
using System;
using CAEV.PagoLinea.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAEV.PagoLinea.Migrations
{
    [DbContext(typeof(PagoLineaContext))]
    [Migration("20240926045712_create_padron_table")]
    partial class create_padron_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAEV.PagoLinea.Models.CuentaPadron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("getDate()");

                    b.Property<decimal>("IVA")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("iVA");

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int")
                        .HasColumnName("idCuenta");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int")
                        .HasColumnName("idLocalidad");

                    b.Property<int>("IdPadron")
                        .HasColumnType("int")
                        .HasColumnName("idPadron");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("localidad");

                    b.Property<string>("Localizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("localizacion");

                    b.Property<string>("PeriodoFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("periodoFactura");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("razonSocial");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("getDate()");

                    b.HasKey("Id");

                    b.ToTable("CuentasPadron");
                });
#pragma warning restore 612, 618
        }
    }
}
